version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: sql_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo_user -d sql_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
